name: Ask for help
description: I need help with the plugin but I'm not sure it is a bug.
title: "[Help needed]: "
labels: ["ask-for-help"]
assignees:
  - MaelImhof
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the community! We're here to help you. Please fill out the following information to help us understand your issue better.
  - type: textarea
    id: explanation
    attributes:
      label: What's the situation?
      description: Tell us what you want to achieve, what happened and what you tried.
      placeholder: "I'm want to achieve X, but Y happens instead. I tried Z."
    validations:
      required: true
