name: Beta Feedback
description: Give constructive feedback on the beta version of the plugin.
title: "[Feedback]: "
labels: ["beta"]
assignees:
  - MaelImhof
body:
  - type: markdown
    attributes:
      value: |
        Thank you for testing the beta version and to take the time to give feedback!
  - type: textarea
    id: explanation
    attributes:
      label: Feedback
      description: Any constructive feedback is appreciated, even (especially) if everything seems to be working.
      placeholder: "What a wonderful plugin (or not)! I think that..."
    validations:
      required: true
