name: Test

on:
  pull_request:
    branches: ["release", "dev"]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: 'npm'

      - run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies (Jupyter)
        run: |
          python -m pip install --upgrade pip
          pip install notebook jupyterlab

      - id: get-cache-key
        name: "Get Obsidian cache key"
        shell: bash
        run: |
          npx tsx wdio.conf.mts > obsidian-versions-lock.txt
          rm -rf .obsidian-cache

      - name: Cache .obsidian-cache
        uses: actions/cache@v4
        with:
          path: .obsidian-cache
          key: obsidian-cache-${{ matrix.os }}-${{ hashFiles('obsidian-versions-lock.txt') }}

      - name: Run e2e tests
        run: |
          ${{ matrix.os == 'ubuntu-latest' && 'xvfb-run --server-args="-screen 0 1280x1024x24" \\' || '' }}
          npm run test:e2e
        shell: bash
        env:
          WDIO_MAX_INSTANCES: 2
